config/routes.rb
Gustr::Application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'images#index'
  resources :images do
    get :recaption
  end
  # resources :businesses
  # resources :events
  # resources :users
  # resources :keywords do
    # get :autocomplete_keyword_name, on: :collection
  # end
  resources :stories do
    get :wizard
    get :publish
    get :tag
    resources :graphics
  end
  get :storybooks, controller: 'stories'
  get :genres, controller: 'stories'
  get :genre, controller: 'stories'
  get :tags, controller: 'stories'
  get :search, controller: 'stories'
  resources :welcome do
    get :index
  end
  get :privacy, controller: 'welcome'
  get :tos, controller: 'welcome'
  get :welcome1, controller: 'welcome'
  get :welcome2, controller: 'welcome'
  get :about, controller: 'welcome'
  resources :users
end

app/models/story.rb
class Story < ActiveRecord::Base
  GENRES = ["Eating Out","Date Night","Events & Celebrations", "Travel","Health & Wellness","Kid Adventure"]
  has_many :graphics
  has_many :tags
  belongs_to :user
  accepts_nested_attributes_for :graphics
  serialize :tags
  serialize :mom
  serialize :time1
  serialize :time2
  geocoded_by :location

  def tagged_by(ip, tag)
    Tag.where(place_id: self.id, user_ip: ip, tag: tag).present?
  end
  def self.published
    self.where('visible is true').where('storybook is not null')
  end

  def as_json(options={})
    geocode
    super
  end

  def location
    "#{place_name} #{city}"
  end
end

app/controllers/stories_controller.rb
class StoriesController < InheritedResources::Base
  respond_to :json
  before_filter :authenticate_user!, only: [:wizard, :tag, :publish, :storybooks]
  def new
    @story = Story.new
  end

  def create
    super { story_wizard_path(@story, page: 0) }
  end

  def update
    if params["story"].has_key?("city") && params["story"].has_key?("nifty")
      super { story_path(@story) }
    else
      super { story_wizard_path(@story, page: @story.step) }
    end
  end

  def publish
    story = Story.find(params[:story_id])
    story.update_attributes!(visible: true)
    tracker.track(user_id, "Publish story")
    redirect_to storybooks_path
  end

  def wizard
    @story = Story.find(params[:story_id])
    if params[:newtitle].present?
      @story.update_attributes!(storybook: params[:newtitle])
      @story.update_attributes!(step: 1)
    end
    @n = (params[:page].presence || @story.step || 0).to_i
    tracker.track(user_id, "Step #{@n}")
    unless @story.step == 6
      render "stories/page"
    else
      redirect_to story_path(@story)
    end
  end

  def tag
    @story = Story.find(params[:story_id])
    if current_user.id == @story.user_id
      @ip = request.ip
      @story = Story.find(params[:story_id])
      tag = Tag.where(user_ip: @ip, tag: params[:tag], story_id: params[:story_id])
      if tag.present?
        tag.first.destroy!
        tracker.track(user_id, "Untag")
      else
        tag = Tag.create!(user_ip: @ip, tag: params[:tag], story_id: params[:story_id])
        tracker.track(user_id, "Tag")
      end
    end
    render :show
  end

  def tags
    @stories = Tag.send(params[:tags]).map(&:story).select{|story| story.visible == true }.select{|story|story.storybook != nil}.uniq
  end

  def search
    tracker.track(user_id, "Search")
  end

  def storybooks
    @stories = Story.where(user_id: current_user.id)
    @story_hash = {}
    @stories.each do |story|
      @story_hash[story.storybook] ||= []
      @story_hash[story.storybook] << story
    end
  end

  def genres
  end

  def genre
    @genre = params[:genre]
    @stories = Story.published.where(genre: @genre)
  end

  def permitted_params
    params.permit(story: [:user_id, :storybook, :title, :genre, :expensive, :place_name, :city, {time1: []}, {time2: []}, :step, :why, :adventure, :nifty, :wise, {mom: []}])
  end

end

app/views/stories/_page1.html.haml
%h2 Add to existing storybook
%ul#buttons
  .story
    -Story.where(user_id: current_user.id).map(&:storybook).map(&:presence).compact.uniq.each do |sb|
      %li.btn=link_to sb, "/stories/#{@story.id}/wizard?&newtitle=#{sb}"
#content
  %h2 Add to new storybook.
  Give your Storybook a title.
  =f.input :step, as: :hidden, input_html: { value: 1 }
  =f.input :storybook, label: false, placeholder: "Storybook title examples: Irish Bars, Chinese Restaurants, Cupcake Shops, etc."
  - if current_user
    =f.input :user_id, as: :hidden, input_html: {value: current_user.id}

app/views/stories/_page2.html.haml
Place/Establishment name
= f.input :place_name, placeholder: "name of the place or location for this chapter...", label: false, required: true
#smallmap
Expensive?
%p
= f.input :expensive, as: :radio_buttons, collection: ["$","$$","$$$"], label: false, required: true
%p
Best time to go
%p
= f.input :time1, as: :check_boxes, collection: ["Breakfast","Lunch","Dinner"], label: false, required: true
= f.input :time2, as: :check_boxes, collection: ["Weekday","Weekend"], label: false, required: true
%p

app/views/stories/_page3.html.haml
Stands out
= f.input :nifty, label: false, placeholder: "Tell people what makes this place special, awesome, worth their while.", required: true

app/views/stories/_page4.html.haml
The Neighborhood
= f.input :adventure, label: false, placeholder: "Are there other exciting or interesting things to do around this place? How accessible is it to public transportation or other modes of transportation? etc.", required: true

app/views/stories/_page5.html.haml
Word to the wise!
= f.input :wise, label: false, placeholder: "This is where you tell us the 'know before you go' about this story.", required: true

app/views/stories/_progress.html.haml
Share your story.
%table.progress{cellpadding: 0, cellspacing: 0}
  -num.times do |i|
    %td.green
      =link_to i, story_wizard_path(@story.id, page: i + 1)
  -(6 - num).times do |i|
    %td
      =link_to i, story_wizard_path(@story.id, page: i + 1)

app/views/stories/edit.html.haml
=simple_form_for @story do |f|
  -6.times do |i|
    =render "page#{i + 1}", f: f
  =f.submit

app/views/stories/genre.html.haml
%h1=@genre
-@stories.each do |story|
  = render story

app/views/stories/genres.html.haml
%h1 Genres
%ul#buttons
  -Story::GENRES.each do |genre|
    %li.btn= link_to genre, genre_path(genre: genre)

app/views/stories/page6.html.haml
.genre Genre: #{@story.genre}
.title Story Title: #{@story.title}
.city City: #{@story.city}
%hr
.time1=@story.time1
.time2=@story.time2
%hr
Why did you go?
.why=@story.why
%hr
What adventure did you choose?
.adventure=@story.adventure
%hr
What's the nifty or thrifty of it?
.nifty=@story.nifty
%hr
Word to the wise!
.wise=@story.wise
%hr
Would you take your mom?
.mom=@story.mom
%hr

app/views/stories/search.html.haml
%table.datatable
  %thead
    %tr
      %th Storybook
      %th Genre
      %th Chapter
      %th City
      %th Tags
      %th By
  - Story.published.each do |story|
    %tr
      %td= story.storybook
      %td= story.genre
      %td= link_to story.place_name.split(',')[0], story
      %td= story.city
      %td= story.tags.map(&:tag).map(&:titleize).to_sentence
      %td= story.user

app/views/stories/show.html.haml
%p
.genre
  %h2 Genre: #{@story.genre}
  %h2 Storybook: #{@story.storybook}
%p
.title
  %h2 Chapter Title: #{@story.place_name.try{|story| story.split(",").first}}
  - user = User.find(@story.user_id) if @story.user_id
  - if user
    %h2 by: #{link_to user, user}
#map-canvas
%p
#{@story.city}
.prevnext
  - if (stories = Story.published.where(storybook: @story.storybook).reject{|story|story.id == @story.id}).count > 1
    - if (left = stories.select { |story| story.id < @story.id }.last)
      .btn_green.hover
        = link_to "<", left
    - if (right = stories.select { |story| story.id > @story.id }.last)
      .btn_green.hover
        = link_to ">", right
  - elsif stories.count == 1
    .btn_green.hover
      = link_to ">", stories.first

- if @story.graphics.present?
  %p
  .images
    .header
      Story Photos
    %ul
      -@story.graphics.each do |graphic|
        %li
          =image_tag(graphic.upload.thumb.url)

%p
= simple_form_for [@story, @story.graphics.build] do |f|
  = f.input :story_id, as: :hidden,input_html: {value: @story.id}
  = f.input :upload
  = f.submit
%p
.taglist.images
  .header
    Hot Tags
  %table.tags.refresh
    - Tag::TAGS.in_groups_of(5).each do |group|
      %tr
      - group.compact.each do |tag|
        %td.hover{class: @story.tags.where(tag: tag.underscore).present? ? 'green' : 'gray'}
          - if current_user && @story.user_id == current_user.id
            = link_to tag, story_tag_path(@story, tag: tag.underscore), remote: true, class: 'togLink'
          - else
            = link_to tag, tags_path(tags: tag.underscore)
%p
.citytime
  %br
  =Array.wrap(@story.time1).try {|time1| time1.map(&:presence).try(:compact)}.try(:to_sentence)
  %br
  =Array.wrap(@story.time2).try {|time1| time1.map(&:presence).try(:compact)}.try(:to_sentence)
%p
%h2 Stands out
.adventure=@story.adventure
%p
%h2 The Neighborhood
.nifty=@story.nifty
%p
%h2 Word to the wise!
.wise=@story.wise
%p
%h2 Scribbles
.why=@story.why
%p
%h2 Would you take your mom?
.mom=Array.wrap(@story.mom).try {|mom| mom.map(&:presence).try(:compact)}.try(:to_sentence)
%p
- if current_user && @story.user_id == current_user.id
  .buttons
    =link_to "Edit story", edit_story_path(@story), class: 'button'
    - if @story.visible == nil || @story.visible == false
      =link_to "Publish story", story_publish_path(@story), class: 'button'
%p

app/views/stories/storybooks.html.haml
%h1 My Storybooks
%p
-@story_hash.keys.each do |storybook|
  %h2=storybook
  -@story_hash[storybook].each do |story|
    =render story

app/views/stories/tags.html.haml
- @stories.each do |story|
  = render story