config/routes.rb
Gustr::Application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'images#index'
  resources :images do
    get :recaption
  end
  # resources :businesses
  # resources :events
  # resources :users
  # resources :keywords do
    # get :autocomplete_keyword_name, on: :collection
  # end
  resources :stories do
    get :wizard
    get :publish
    get :tag
    resources :graphics
  end
  get :storybooks, controller: 'stories'
  get :genres, controller: 'stories'
  get :genre, controller: 'stories'
  get :tags, controller: 'stories'
  get :search, controller: 'stories'
  resources :welcome do
    get :index
  end
  get :privacy, controller: 'welcome'
  get :tos, controller: 'welcome'
  get :welcome1, controller: 'welcome'
  get :welcome2, controller: 'welcome'
  get :about, controller: 'welcome'
  resources :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :upload, ImageUploader
  belongs_to :user
  has_many :recaptions, class_name: Image, foreign_key: :parent_id
  belongs_to :parent, class_name: Image
end

app/controllers/images_controller.rb
class ImagesController < InheritedResources::Base
  respond_to :html, :json
  def permitted_params
    params.permit(image: [:upload, :caption, :user_id, :posX, :posY, :width, :height, :question1, :question1a, :question2, :question2a, :question3, :question4])
  end

  def index
    @image = Image.new
    @user_id = current_user.try(&:id) || request.ip.gsub(".","").gsub(":","")
    super
  end

  def new
    @user_id = current_user.try(&:id) || request.ip.gsub(".","").gsub(":","")
    super
  end

  def show
    @image = Image.find(params[:id])
    @editable = (current_user && (@image.user_id == current_user.id)) || (@image.user_id == request.ip.gsub(".","").gsub(":",""))
    super
  end

  def update
    super { images_path }
  end

  def edit
    @image = Image.find(params[:id])
    if @image.parent_id
      redirect_to image_path(@image.parent_id)
    else
      redirect_to images_path
    end
  end

  def recaption
    @image = Image.find(params[:image_id])
    image = Image.new
    image.upload = @image.upload
    image.parent_id = @image.id
    if current_user
      image.user_id = current_user.id
    else
      image.user_id = request.ip.gsub(".","").gsub(":","")
    end

    image.save!
    redirect_to image_path(image)
  end
end

app/views/images/edit.html.haml
=simple_form_for @image do |f|
  =f.input :question1, as: :radio_buttons, collection: ["Yes","No"], label: "Do you want to continue captioning photos?"
  =f.input :question1a, label: "Why"
  =f.input :question2, label: "When you take a photo, do you like to record in some way the location where you took the photo?", as: :radio_buttons, collection: ["Yes","No"]
  =f.input :question2a, label: "Is there any information about the photos you take that is always important to remember, for example: feelings, time, place, people?"
  =f.input :question3, label: "When you create something artistic, whose recognition do you value more:", collection: ["Strangers'","Friends'","Relatives'"]
  =f.input :question4, label: "What is missing from your photo captioning experience?"
  =f.submit "Continue"

app/views/images/index.html.haml
=simple_form_for @image do |f|
  =f.input :user_id, input_html: { value: @user_id }, as: :hidden
  =f.input :upload, label: "Select Photo"
%p
%ul.images
  -@images.where(parent_id: nil).sort_by(&:created_at).reverse.each_with_index do |image, index|
    %li.image
      .imagebox
        =link_to image_tag(image.upload.small.url), image_path(image)
        .floater.visible{data: {width: image.width, height: image.height, left: image.posX, top: image.posY + index*555+79}}
          .caption
            =image.caption.try(&:html_safe)

app/views/images/new.html.haml
=simple_form_for @image do |f|
  =f.input :user_id, input_html: { value: @user_id }, as: :hidden
  =f.input :upload, label: "Select Photo"

app/views/images/show.html.haml
.imagebox
  .editable= @editable
  =image_tag @image.upload.small.url
  .floater.visible{data: {width: @image.width, height: @image.height, left: @image.posX, top: @image.posY}}
    .caption
      =@image.caption.try(&:html_safe)
    -if @editable
      %textarea
      .ok
        Save
  -if @editable
    = simple_form_for @image do |f|
      = f.input :place_name, placeholder: "name of the place or location for this chapter...", label: false, required: true
    .post
      =button_to "Post", edit_image_path(@image), method: :get
  -else
    .recaption
      =button_to "Recaption", image_recaption_path(@image), method: :get
%p
%ul.images
  - if @image.recaptions.present?
    #{@image.recaptions.count} recaptions
    %p
    - @image.recaptions.each_with_index do |recap, index|
      %li.image
        .imagebox
          =link_to(image_tag(recap.upload.small.url), image_path(recap))
          .floater.visible{data: {width: recap.width, height: recap.height, left: recap.posX, top: recap.posY + (index+1)*555+50}}
            .caption
              =recap.caption.try(&:html_safe)